import os
import re

from ..helper.auto_numbered import AutoNumberedEnum


__all__ = ["ExportAdapterFormat", "ExportAdapter"]


class ExportAdapterFormat(AutoNumberedEnum):
    CSV = ()


class ExportAdapter:
    def __init__(self, path: str = "a.out") -> None:
        self.__path = path
        try:
            os.makedirs(os.path.dirname(self.__path))
        except (FileExistsError, FileNotFoundError):
            pass

    def export(
        self, topic: str, sentiment: str, data: str, format: ExportAdapterFormat = ExportAdapterFormat.CSV
    ) -> None:
        match format:
            case ExportAdapterFormat.CSV:
                with open(self.__path, "a", encoding="utf-8") as f:  # add to file
                    # data is a text generated by the model
                    # it should contain a list of tweets beginning with a number and a dot (1. )
                    # and ending with a newline
                    tweets: list[str] = re.findall(r"\d+\.\s.*\n", data)
                    for tweet in tweets:
                        f.write(f"{topic}\t{sentiment}\t{tweet}\n")
            case _:
                raise NotImplementedError(f"Export format {format} is not supported.")
